version: '3.8'

# ============================================
# AccountBox - MySQL Test Environment
# ============================================
# MySQL 测试环境配置 - 仅启动数据库和管理工具
# 用于本地开发和测试
#
# 启动方式:
#   docker-compose -f docker-compose.mysql-test.yml up -d
#
# 访问方式:
#   - MySQL: localhost:3306
#   - phpMyAdmin: http://localhost:8080
# ============================================

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: accountbox-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: accountbox
      MYSQL_USER: accountbox
      MYSQL_PASSWORD: accountbox123
    ports:
      - "3306:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
    networks:
      - accountbox-test-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "accountbox", "-paccountbox123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # phpMyAdmin 数据库管理工具
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: accountbox-phpmyadmin-test
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: accountbox
      PMA_PASSWORD: accountbox123
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - accountbox-test-network

networks:
  accountbox-test-network:
    driver: bridge

volumes:
  mysql-test-data:
    driver: local
