version: '3.8'

services:
  # 后端 API 服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: accountbox-backend
    restart: unless-stopped
    ports:
      - "5093:5093"
    volumes:
      # 持久化数据库
      - accountbox-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_PATH=/app/data/accountbox.db
      - ASPNETCORE_URLS=http://+:5093
    networks:
      - accountbox-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5093/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # 前端 Web 应用
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: accountbox-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - accountbox-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  accountbox-network:
    driver: bridge

volumes:
  accountbox-data:
    driver: local
