version: '3.8'

services:
  backend:
    image: docker.cnb.cool/rich/public/accountbox:latest
    container_name: accountbox
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5093}:8080"
    volumes:
      - backend-data:/app/data
    environment:
      DB_PROVIDER: ${DB_PROVIDER:-postgresql}
      CONNECTION_STRING: ${CONNECTION_STRING}
      MASTER_PASSWORD: ${MASTER_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend-data:
    driver: local
