version: '3.8'

services:
  # 单镜像部署 - 包含前端和后端
  accountbox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-1.0.0}
    container_name: accountbox-all-in-one
    restart: unless-stopped
    ports:
      - "5093:5093"  # API 和前端都通过这个端口访问
    volumes:
      # 持久化数据库
      - accountbox-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_PATH=/app/data/accountbox.db
      - ASPNETCORE_URLS=http://+:5093
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5093/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  accountbox-data:
    driver: local
