openapi: 3.0.3
info:
  title: AccountBox - PasswordGenerator API
  description: 密码生成器API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api

paths:
  /password-generator/generate:
    post:
      summary: 生成密码
      operationId: generatePassword
      tags:
        - PasswordGenerator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneratePasswordRequest'
      responses:
        '200':
          description: 生成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratePasswordResponse'

  /password-generator/strength:
    post:
      summary: 计算密码强度
      operationId: calculateStrength
      tags:
        - PasswordGenerator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateStrengthRequest'
      responses:
        '200':
          description: 计算成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordStrengthResponse'

components:
  schemas:
    GeneratePasswordRequest:
      type: object
      required:
        - length
        - includeLowercase
        - includeUppercase
        - includeDigits
        - includeSymbols
      properties:
        length:
          type: integer
          minimum: 8
          maximum: 128
          example: 16
        includeLowercase:
          type: boolean
          example: true
        includeUppercase:
          type: boolean
          example: true
        includeDigits:
          type: boolean
          example: true
        includeSymbols:
          type: boolean
          example: true
        excludeAmbiguous:
          type: boolean
          description: 排除易混淆字符（0/O, 1/l/I等）
          example: true

    GeneratePasswordResponse:
      type: object
      required:
        - password
        - strength
        - entropy
      properties:
        password:
          type: string
          example: "A3k@9xL#2mP&5vQ!"
        strength:
          type: string
          enum: [weak, medium, strong]
          example: strong
        entropy:
          type: number
          description: 熵值（bits）
          example: 95.2

    CalculateStrengthRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          example: "MyP@ssw0rd"

    PasswordStrengthResponse:
      type: object
      required:
        - strength
        - entropy
        - charsetSize
      properties:
        strength:
          type: string
          enum: [weak, medium, strong]
          example: medium
        entropy:
          type: number
          example: 65.4
        charsetSize:
          type: integer
          description: 字符集大小
          example: 72

security:
  - VaultSession: []
