// <auto-generated />
using System;
using AccountBox.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountBox.Data.Migrations
{
    [DbContext(typeof(AccountBoxDbContext))]
    partial class AccountBoxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AccountBox.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedData")
                        .IsRequired()
                        .HasMaxLength(10240)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("NotesEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("NotesIV")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("NotesTag")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordIV")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Username");

                    b.HasIndex("WebsiteId");

                    b.HasIndex("WebsiteId", "IsDeleted");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("AccountBox.Data.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPlaintext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("VaultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeyPlaintext")
                        .IsUnique();

                    b.HasIndex("VaultId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("AccountBox.Data.Entities.ApiKeyWebsiteScope", b =>
                {
                    b.Property<int>("ApiKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApiKeyId", "WebsiteId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("ApiKeyWebsiteScopes");
                });

            modelBuilder.Entity("AccountBox.Data.Entities.KeySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Argon2Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Argon2MemorySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Argon2Parallelism")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Argon2Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedVaultKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("VaultKeyIV")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("VaultKeyTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("KeySlots", null, t =>
                        {
                            t.HasCheckConstraint("CK_KeySlot_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("AccountBox.Data.Entities.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("Websites", (string)null);
                });

            modelBuilder.Entity("AccountBox.Data.Entities.Account", b =>
                {
                    b.HasOne("AccountBox.Data.Entities.Website", "Website")
                        .WithMany("Accounts")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("AccountBox.Data.Entities.ApiKey", b =>
                {
                    b.HasOne("AccountBox.Data.Entities.KeySlot", "Vault")
                        .WithMany()
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("AccountBox.Data.Entities.ApiKeyWebsiteScope", b =>
                {
                    b.HasOne("AccountBox.Data.Entities.ApiKey", "ApiKey")
                        .WithMany("ApiKeyWebsiteScopes")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountBox.Data.Entities.Website", "Website")
                        .WithMany()
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("AccountBox.Data.Entities.ApiKey", b =>
                {
                    b.Navigation("ApiKeyWebsiteScopes");
                });

            modelBuilder.Entity("AccountBox.Data.Entities.Website", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
